server:
  port: 8084

spring:
  application:
    name: basicInformation
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.106.193:8848
  datasource:
    druid:
      username: neusoft
      password: "12345"
      url: jdbc:mysql://49.232.199.44:3306/bsp_database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*/*Mapper.xml
  type-aliases-package: com.neusoft.basicinformation8084.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
